
Neos:
  Neos:
    fusion:
      autoInclude:
        "Sitegeist.Monocle.PresentationObjects": true
  Fusion:
    defaultContext:
      "Monocle.PresentationObjects": Sitegeist\Monocle\PresentationObjects\Infrastructure\PresentationObjectHelper
